### ISSUE TITLE
Reported framerate isn't accurate

### ISSUE THREAD

**Issue by Stuntaneous** [DevL0rd/SkyNX#16]
I.e. framerate looks perfectly fine in the corner of the Windows program while on the Switch it regularly gets choppy.

**Comment by oocyberkevinoo** [comment]
He already have this information in the other issue report that you even answered in ^^'
Certainly it is because he fetch the framerate informations before sending it to the Nintendo Switch.
At least, that mean the video recorded to stream should be 60FPS, but once it goes to the Switch, it is not :/

**Comment by DevL0rd** [comment]
^ Yeah exactly, I'll make a new protocol for sending stats from the switch in the next update.

**Comment by DevL0rd** [comment]
Donzo.
