### ISSUE TITLE
Cannot connect to my switch/PC at all. :(

### ISSUE THREAD

**Issue by addictedgmr** [DevL0rd/SkyNX#4]
I enter the IP, and it just refuses to connect.

https://streamable.com/kcquod

**Comment by DevL0rd** [comment]
oh no XD Lets work out what the problem is here.
1. Do you have a 32 or 64 bit system?
2. Open the streamer folder.
3. Then open the NxStreamingService folder
4. Shift right click anywhere and open a powershell window
5. run .\NxStreamingService.exe -ip yourswitchip  /q 4
3. Then paste me the log here and I'll push an update as soon as I can to fix.

**Comment by xlim3y** [comment]
I followed your steps here Dev and got the following:

Error: Usage NXStreamer.exe ip 0.0.0.0 q 5

**Comment by addictedgmr** [comment]
![dev](https://user-images.githubusercontent.com/31566519/80034701-ae7a2e80-84a3-11ea-8045-1c1fba843981.PNG)

**Comment by DevL0rd** [comment]
oh my gosh XD. ok i'll patch it in this upcoming release.

**Comment by DevL0rd** [comment]
oh wait hey.
run this instead. i did a / on accident 

.\NxStreamingService.exe -ip yourswitchip  -q 4

**Comment by addictedgmr** [comment]
same thing

![ayu](https://user-images.githubusercontent.com/31566519/80035551-12512700-84a5-11ea-9ed7-7454eb9e29e0.PNG)

**Comment by xlim3y** [comment]
yeah same here

**Comment by DevL0rd** [comment]
ok last time XD i'm dumb. i forget that node doesn't parse '-'.
use slashes instead... sorry guys...

.\NxStreamingService.exe /ip yourswitchip /q 4

**Comment by addictedgmr** [comment]
this def seems the most helpful

![Uploading 7.PNG…]()

**Comment by DevL0rd** [comment]
oh ok. you need to isntall the controller driver. the next version does this automatically. try installing it in the settings menu. I'll post here when I release the next one which does it automatically.

**Comment by DevL0rd** [comment]
Releasing that version in like an hour.

**Comment by xlim3y** [comment]
Yup that fixed it, soon as I manually installed the driver it was perfect.

Thanks man!

**Comment by xlim3y** [comment]
One more thing, can you add an option to minimize to systray?

I'd like to leave it up on my streaming machine permanently, so having it live in the system tray would be great.

**Comment by addictedgmr** [comment]
^^^

**Comment by xlim3y** [comment]
So i've discovered something else.

When I run a game that requires UAC elevation, the stream drops when it prompts me to confirm that it's ok to run the application.  I have to stop and manually restart the stream.

**Comment by addictedgmr** [comment]
disable the UAC prompts.

**Comment by DevL0rd** [comment]
Idk about the UAC rpompt thing, that is odd. I'll look at it but mine are disabled.

And I would LOVE minimize to sys tray too but it's on the backburner for a minute.

Next release coming in like 20 minutes. So definitely download and try out.

Won't need that other software for audio now as it is built in. And jsut because of this issue i added a built in console haha
