### ISSUE TITLE
Stuck on ip address screen. No audio no video. But I can move pc cursor by touching switch's screen

### ISSUE THREAD

**Issue by orangpelupa** [DevL0rd/SkyNX#43]
On windows 10.

**Comment by MrSnoozles** [comment]
Which encoder?

**Comment by DevL0rd** [comment]
Can you post the console log?

**Comment by geo552** [comment]
Same problem 
![consolelog](https://user-images.githubusercontent.com/40296602/83510597-eed2c080-a4d5-11ea-8c62-d9b4d9e7a388.png)

**Comment by pr0dukt** [comment]
I have the exact same issue as well, and it used to work perfectly for me prior to some recent updates, and a CFW switch to Nilla AMS from kosmos. Not likely relevant, but its the most recent "change" in my switch's environment that I can think of. 

Console just spams bitstream data for audio, and "SwitchFPS=o" like in the screenshot above. 
Any inclinations as to what the root cause of no video feed might be? Switch screen just stays idle on the initial SkyNX IP address screen with no change when connected.

**Comment by DevL0rd** [comment]
It says the nvidia codec wasn't loading because it didn't detect a recent enough version of their drivers.

If you are not using a nvidia you it definitely won't work of course but if you have one, have you guys checked what version if the graphics drivers you are running?
