### ISSUE TITLE
Low framerates on switch

### ISSUE THREAD

**Issue by valmcc** [DevL0rd/SkyNX#5]
Hey, first up, great work getting this going again! 
I've had a play around with it, and I'm noticing pretty low framerates on the switch. This is despite keeping a constant 60fps on my computer (I've tried with just ffmpeg video only, using the same command line args) 

Reference below while running Sekiro on the laptop: 
![stream](https://user-images.githubusercontent.com/20529815/79987643-07bc7f00-84f1-11ea-98b0-fd55699a54dc.PNG)

This is with the switch connected to the wireless router via 5ghz, and the computer connected to the router via ethernet. 

I also tried using sys-clk to overclock the switch cpu to the maximum clock rate and the video still seems like it's at a low framerate.

I did get much better framerates (close to 60fps) with the option:
> -tune fastdecode

but this makes the latency quite high.

Wondering if you've got any ideas?

Otherwise, audio seemed great. No glitches at all!

**Comment by DevL0rd** [comment]
I have no issues on mine. then again i have a $300 nighthawk router. But re-download the release nro because i did have stutter on one build and i accidentally uploaded it before immediately replacing it. maybe you got the inbetween build on accident? XD

One more thing is that the app sets your overclock a bit below the max overclock and it works pretty well without it. uses about 32% of the thread it is on. so definitely some performance to be gained somwhere.

I will be working on optimizations soon. I'm going to be splitting the rendering into a few threads and try some experiments to see if i can sync it all together for some better performance. Sadly there is no GPU decoding on switch at the moment so I'm going to need to use the cpu time efficiently. I'll notify you when I release this next build.

**Comment by DevL0rd** [comment]
@valmcc ok go ahead and try the latest release. Let me know how it works for you!

**Comment by valmcc** [comment]
I think I figured it out. I think it's an ffmpeg or gdigrab bug, that when my screen resolution is 1280x720, the output video feed is laggy/slow, and the framerate reported is incorrect. 

 I've noticed that when I use my native resolution of 1920x1080, and instead change the video size so it's capturing the top left-hand corner of my screen, it runs flawlessly.

This is what I've been using, I tried using NVENC but it doesn't fix this problem:
`./ffmpeg.exe -probesize 10M -f gdigrab -framerate 60 -video_size 1280x720 -offset_x 0 -offset_y 0 -i desktop -c:v h264_nvenc -f h264 -vf "scale_npp=1280:720" -preset 9 -pix_fmt yuv420p -zerolatency 1 -b:v 5M -minrate 5M -maxrate 5M -bufsize 1M tcp://192.168.1.108:2222`

A very weird bug, I still haven't gotten to the bottom of it.

**Comment by DevL0rd** [comment]
That is very strange. I'll try it out in my test build here and see what I can get to work aswell.
and I have a nvenc paramaters list in the new one but it has so much latency right now, can't figure out why.

But the reason I chose a region to grab anyway was because when more than one monitor is plugged in it tries to grab all monitors in a large context. I wonder if it has something to do with specifying the region to capture instead of cropping it. But i figured cropping introduced too much latency.

I appreciate you helping with the stream parameters. Let me know if you ever find the fix. XD

**Comment by DevL0rd** [comment]
Um I figured it out. It was the probe size.

Check out my latest release. It is insanely fast....

**Comment by DustinHendrickson** [comment]
Working much better for me at least! Was running around on Sea of Thieves with decent frames!

**Comment by DevL0rd** [comment]
@DustinHendrickson You have no idea how good that is to hear XD

**Comment by valmcc** [comment]
Can confirm it's much smoother now, I still have that weird ffmpeg bug though.

**Comment by DevL0rd** [comment]
> Can confirm it's much smoother now, I still have that weird ffmpeg bug though.

Yeah ffmpeg is probing the framerate so it eventually evens out though. ffmpeg is still a little confusing to me lol
