### ISSUE TITLE
Nothing happend. Just 'Waiting for connection'

### ISSUE THREAD

**Issue by paragon89** [DevL0rd/SkyNX#57]
Hi. thanks for developing this streaming app. 
But I have a little problem with my PC.

It is okay when I streaming my laptop. And everything are working properly.
But with PC, there's only message 'waiting for connection' appeared below.

And console tab, there are same error message came out repeatedly.
'Could not connect to Switch, Connection timed out....'

Please help me streaming PC.
I hope you understand my situation with this short English.

**Comment by LarsonRogers** [comment]
I'd suggest looking through the forum post on GBATemp [here](https://gbatemp.net/threads/skynx-v1-0-stream-your-pc-games-to-your-nintendo-switch.563403/), as this seems like more of a configuration issue since your laptop is working fine. If you describe your problem there, you might find others who've experienced similar difficulties who will be more than happy to help.
